config/routes.rb
Cabra::Application.routes.draw do
  devise_for :users

  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout
  end

  resources :groups
  resources :leaders
  resources :leadernotes
  resources :locations
  resources :trips
  resources :activities
  resources :users
  resources :reports
  resources :plans do
    member do
      post 'add_trips'
      patch 'confirm_plan'
    end
  end

  root to: "trips#index"

end

app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to :group
  belongs_to :plan
  belongs_to :location
  belongs_to :activity

  has_one :report

  delegate :confirmed?, to: :plan
  delegate :full_address, to: :location

  scope :future, -> { where("date > ?", Date.today) }
  scope :past, -> { where("date <= ?", Date.today) }
  scope :year, -> { where("extract(year from date) = ?", Date.today.year) }
  scope :need_report, -> { select { |trip| trip.report.blank? } }
  scope :adding_trips, -> { where("plan_id IS ?", nil) }

  validates_presence_of :date, :group_id, :location_id, :activity_id, :pickup_time, :dropoff_time


  def google_static_image
    "http://maps.googleapis.com/maps/api/staticmap?maptype=roadmap&sensor=false \
    &center=Greenville%20SC&size=500x300 \
    &markers=color:green%7CGreenville%20SC \
    &markers=color:red%7Clabel:G%7C#{self.full_address} \
    &key=#{ENV['GOOGLE_MAPS_API_KEY']}"
  end
end

app/models/trip_types.rb
class TripTypes < ActiveRecord::Base
  
end

app/models/trips.rb
class Trips < ActiveRecord::Base
  belongs_to :group
  belongs_to :plan

  has_one :trip_type
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  def index
    if current_user.roles_mask === 4 || nil
      params[:type] = 'need_report'
    end
    @trips = Trip.future.paginate(page: params[:page], per_page: 20).order('date ASC')
    @trips_past = Trip.past.paginate(page: params[:page], per_page: 20).order('date DESC')
    @trips_need = Trip.year.past.paginate(page: params[:page], per_page: 20).order('date DESC').need_report
    @groups = Group.all.order('name ASC')
  end
  def new
    if params[:group]
    @group = Group.find(params[:group])
    @trip = Trip.new
    else
    redirect_to groups_path, notice: 'Select a group to make a trip'
    end
  end
  def create
    @trip = Trip.new(trip_params)
    if @trip.save
      redirect_to trips_path, notice: 'Trip created successfully'
    else
      params[:group] = params[:trip][:group_id]
      @group = Group.find(params[:group])
      render :new, group: params[:group]
    end
  end
  def show
    @trip = Trip.find(params[:id])
    @location = Location.find(@trip.location_id)
    @group = Group.find(@trip.group)
  end
  def edit
    @trip = Trip.find(params[:id])
  end
  def update
    @trip = Trip.find(params[:id])
    if @trip.update_attributes(trip_params)
      redirect_to trips_path, notice: 'Trip successfully updated!'
    else
      render "edit"
    end
  end
  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy
    redirect_to trips_path, notice: 'Trip deleted.'
  end

    private

    def trip_params
      params.require(:trip).permit(
        :activity_id, :location_id, :group_id, :scheduled_participants,
        :actual_participants, :plan_id, :pickup, :pickup_time, :dropoff_time,
        :date, :lunch
      )
    end
end

app/views/trips/_form.html.erb
<%= simple_form_for(@trip, html: { class: 'form-inline' }) do |f| %>
  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% @trip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-4">
      <%= f.input :scheduled_participants %><br /><br />
    </div>
      <div class="col-md-4">
      <%= f.input :location_id, collection: Location.all, label_method: :name, html: { class: "form-control"} %>
      <br /><br />

      <%= f.input :activity_id, collection: Activity.all, label_method: :name %>
      <br /><br />

      <%= f.input :pickup, as: :boolean, boolean_style: :inline %>

      <%= f.input :lunch, as: :boolean, boolean_style: :inline %>
    </div>
    <div class="col-md-4">
      <%= f.label "Trip date" %> <br />
      <%= f.date_field :date, :id => 'datepicker' %> <br /><br />

      <%= f.label "Pickup time" %><br />
      <%= f.input :pickup_time, input_html: { class: 'time-input' } %><br /><br />

      <%= f.label "Dropoff time" %><br />
      <%= f.input :dropoff_time, input_html: { class: 'time-input' } %><br /><br />
    </div>
  </div>

    <% if params[:group].present? %>
      <%= f.hidden_field :group_id, value: params[:group] %>
    <% end %>

    <center>
      <%= f.submit class: "btn btn-primary" %>
    </center>
  <% end %>

app/views/trips/edit.html.erb
Edit Trip

<%= render 'form' %>


  <br /><br /><br /><br /><br /><br />

  <div class="alert alert-danger col-md-4 col-md-offset-4">
    <b><%= link_to 'Click here to delete this trip (this cannot be undone)', url_for(action: :destroy, id: @trip.id),method: :delete, data: {confirm: "Are you sure? This cannot be undone"} %></b>
  </div>

app/views/trips/index.html.erb
<% unless current_user.has_role?(:admin) || current_user.has_role?(:reporter) %>
  <h1>Unauthorized</h1>
  <p>You are not authorized to use Alpha, or have not yet been added by an admin. If you need to be authorized, please contact an admin.</p>

  <h3>If you are a group looking for your plans or trips, please use the link provided in your email. You do not need an account or to login</h3>

<% else %>
  <button class="btn btn-primary" data-toggle="modal" data-target=".trip-modal">Create new trip</button>
  <br /><br />

  <% if @trips.empty? && @trips_past.empty? %>

    <h1>You haven't created any trips yet, go select a group to make a trip</h1>

  <% else %>

    <% if params[:type] == "past" %>
      <!-- past trips -->
      <h4>Past trips</h4>
      <%= link_to "View Upcoming Trips", trips_path %>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <td><b>Trip Date</b></td>
            <td><b>Group Name</b></td>
            <td><b>Trip Location</b></td>
            <td><b></b></td>
            <td></td>
            <td align="center"><b>Plan?</b></td>
            <td align="center"><b>Report?</b></td>
          </tr>
        </thead>

        <% @trips_past.each do |trip| %>
          <tr>
            <td><%= trip.date.strftime("%b %d, %Y") %></td>
            <td><%= trip.group.name %></td>
            <td><%= trip.location.name %></td>
            <td><%= link_to "View", trip_path(trip) %></td>
            <td><%= link_to "Edit", edit_trip_path(trip) %></td>
            <td align="center">
              <% if trip.report.nil? %>
                <span class="glyphicon glyphicon-ok"></span>
              <% end %>
            </td>
            <td align="center">
              <% if trip.report.nil? %>
                <span class="glyphicon glyphicon-exclamation-sign red"> </span><%= link_to "Report", new_report_path(:trip => trip) %>
              <% else %>
                <span class="glyphicon glyphicon-ok-circle green">
              <% end %>
            </td>
          </tr>
        <% end %>
        </table>
        <center><%= will_paginate @trips_past %></center>

      <% elsif params[:type] == "need_report" %>

      <% if @trips_need.empty? %>
        <h1>All done here, good job kiddos!</h1>
      <% else %>
        <!-- past trips without reports -->
        <h4>Trips that need reports</h4>
        <%= link_to "View Upcoming Trips", trips_path %>
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <td><b>Trip Date</b></td>
              <td><b>Group Name</b></td>
              <td><b>Trip Location</b></td>
              <td><b></b></td>
              <td><b>Report</b></td>
            </tr>
          </thead>
          <% @trips_need.each do |trip| %>
            <tr>
              <td><%= trip.date.strftime("%b %d, %Y") %></td>
              <td><%= trip.group.name %></td>
              <td><%= trip.location.name %></td>
              <td><%= link_to "View Trip", trip_path(trip) %></td>
              <td><%= link_to "Create Report", new_report_path(:trip => trip) %></td>
            </tr>
          <% end %>
        </table>
        <center><%= will_paginate @trips_past %></center>
      <% end %><!-- if @trips_past empty? -->

    <% else %>

      <!-- future trips (default) -->
      <h4>Upcoming Trips</h4>
      <% if @trips.empty? %>
        <h3>You have no upcoming trips listed, view <%= link_to "past trips", trips_path( :type => "past" ) %> here</h3>
      <% else %>
        <%= link_to "View Past Trips", trips_path( :type => "past" ) %>
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <td><b>Trip Date</b></td>
              <td><b>Group Name</b></td>
              <td><b>Trip Location</b></td>
              <td><b></b></td>
              <td><b></b></td>
              <td><b>Plan?</b></td>
              <td><b>Confirmed?</b></td>
              <td><b></b></td>
            </tr>
          </thead>
          <% @trips.each do |trip| %>
            <tr>
              <td><%= trip.date.strftime("%b %d, %Y") %></td>
              <td><%= trip.group.name %></td>
              <td><%= trip.location.name %></td>
              <td><%= link_to "View", trip_path(trip) %></td>
              <td><%= link_to "Edit", edit_trip_path(trip) %></td>
              <td>
                <% if trip.plan.nil? %>
                  &nbsp;
                <% else %>
                  <%= link_to plan_path(trip.plan) do %><span class="glyphicon glyphicon-ok"><% end %></span>
                <% end %>
              </td>
              <td>
                <% if trip.plan && trip.confirmed? %>
                  <span class="glyphicon glyphicon-ok"></span>
                <% end %>
              </td>
              <td>
                <%= link_to 'delete', url_for(action: :destroy, id: trip.id),method: :delete, data: {confirm: "Are you sure?"} %>
              </td>
            </tr>
          <% end %>
        </table>
      <% end %>
      <center><%= will_paginate @trips %></center>
    <% end %>

  <% end %>


  <div class="modal fade trip-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-content">
      <div class="modal-dialog modal-sm">
        <div class="modal-title">Select a group to create a trip</div>
          <div class="modal-body">
            <% @groups.each do |group| %>
              <%= group.name %>
              <%= link_to "New Trip", new_trip_path( :group => group ) %><br />
            <% end %>
          </div>
      </div>
    </div>
  </div>
<% end %>

app/views/trips/new.html.erb
<h3>New trip for <b><%= @group.name %></b></h3><br /><br />

<%= render 'form' %>

app/views/trips/show.html.erb
<h3><%= @group.name %>'s <%= @trip.activity.name %> trip on <b><%= @trip.date.strftime("%B %d, %Y") %></b></h3>
<br /><br />

<div class="row">
  <div class="col-md-3">
    <% if @trip.pickup == false %>
      <h4>Meet at <%= @trip.location.name %></h4>
    <% else %>
      <h4>Pickup at <%= @trip.group.name %></h4>
    <% end %>
    <hr />
    <h4><%= string_to_time(@trip.pickup_time) %></h4>
    <br /><br />
    <% if @trip.pickup == false %>
      <h4>Departure</h4>
    <% else %>
      <h4>Return</h4>
    <% end %>
    <hr />
    <h4><%= string_to_time(@trip.dropoff_time) %></h4>
  </div>
  <div class="col-md-3">
    <h4># of participants</h4>
    <hr />
    <h4><%= @trip.scheduled_participants %></h4>
    <br /><br />
    <h4>Location</h4>
    <hr />
    <h4><%= @location.name %></h4>
    <h4><%= @location.street %></h4>
    <h4><%= @location.city %>, <%= @location.state %> <%= @location.zip %></h4>
  </div>

  <div class="col-md-6">
    <h4>Directions: <%= link_to @trip.full_address, "http://maps.google.com/?q=#{@trip.full_address}" %></h4>
    <%= image_tag @trip.google_static_image %>
  </div>
</div>