config/routes.rb
Cabra::Application.routes.draw do
  devise_for :users

  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout
  end

  resources :groups
  resources :leaders
  resources :leadernotes
  resources :locations
  resources :trips
  resources :activities
  resources :users
  resources :reports
  resources :plans do
    member do
      post 'add_trips'
      patch 'confirm_plan'
    end
  end

  root to: "trips#index"

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :plans
  has_many :trips
  has_many :leaders
  has_many :students

  validates :name, uniqueness: true

end

app/models/groups.rb
class Groups < ActiveRecord::Base
  has_many :plans
  has_many :trips
  has_many :leaders
  has_many :students
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  def index
    @groups = Group.all.order('name ASC')
  end
  def new
    @group = Group.new
  end
  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to groups_path, notice: "Group " + @group.name + " successfully created"
    else
      render "new"
    end
  end
  def show
    @group = Group.find(params[:id])
    @trips = @group.trips.future
    @past_trips = @group.trips.past
  end
  def edit
    @group = Group.find(params[:id])
  end
  def update
    @group = Group.find(params[:id])
    if @group.update_attributes(group_params)
      redirect_to groups_path, notice: @group.name + " successfully updated!"
    else
      render "edit"
    end
  end

    private

    def group_params
      params.require(:group).permit(:name, :street, :city,
                                    :state, :zip)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= simple_form_for(@group, html: {class: 'form-vertical' }) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="input-group">
      <%= f.input :name %>
  </div>

  <div class="input-group">
      <%= f.input :street %>
  </div>

  <div class="input-group">
    <%= f.input :city %>
  
    <%= f.input :state %>

    <%= f.input :zip %>
  </div>
          
  <%= f.submit class: "btn" %>

<% end %>

app/views/groups/edit.html.erb
Edit group:

<%= render "form" %>

app/views/groups/index.html.erb
<%= link_to "Create New Group", new_group_path %>&nbsp;<span class="glyphicon glyphicon-new-window"></span>

<br /><br />

<% if @groups.empty? %>

  <h1>You need to create a group before you can make a trip</h1>

  <h3><%= link_to "Create a New Group", new_group_path %> to get started</h3>

<% else %>

    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <td><b>Group Name</b></td>
          <td><b>City</b></td>
          <td><b>Associated Leaders</b></td>
          <td><b></b></td>
        </tr>
      </thead>
      <% @groups.each do |group| %>
        <tr>
          <td><%= link_to group.name, group_path(group) %></td>
          <td><%= group.city %></td>
          <td>
            <% group.leaders.each do |leader| %>
              <%= link_to leader.full_name, leader_path(leader) %><br />
            <% end %>
          </td>
          <td><%= link_to "Edit", edit_group_path(group) %></td>
        </tr>
      <% end %>
    </table>

<% end %>

app/views/groups/new.html.erb
<h3>New Group</h3>

<%= render 'form' %>

app/views/groups/show.html.erb
<h2><%= @group.name %></h2>
<div class="col-md-4">
    <p><%= @group.street %><br />
    <%= @group.city %>, <%= @group.state %> <%= @group.zip %></p>
    <p>(<%= link_to "Edit Group", edit_group_path(@group) %>)</p>

    <p><%= link_to "New Trip for #{@group.name}", new_trip_path( :group => @group ) %>&rarr;</p>

    <h3>Group Leaders</h3>
    <% @group.leaders.each do |leader| %>
      <%= link_to leader.full_name, leader_path(leader) %><br />
    <% end %>
  </div>
  <div class="col-md-8">
      <% if @trips.empty? && @past_trips.empty? %>
        <%= @group.name %> has no scheduled trips currently
      <% else %>
        <% if params[:type] == "past" %>
          <h3>Past trips</h3>
          (or go back to <%= link_to "upcoming trips", group_path(@group) %>)
          <table class="table table-striped table-hover">
              <thead>
                <tr>
                  <td><b>Trip Date</b></td>
                  <td><b>Trip Location</b></td>
                  <td><b>Trip Activity</b></td>
                  <td><b></b></td>
                  <td><b>Plan?</b></td>
                  <td><b></b></td>
                </tr>
              </thead>  
              <% @past_trips.each do |trip| %>
                <tr>
                  <td><%= trip.date.strftime("%b %d, %Y") %></td>
                  <td><%= trip.location.name %></td>
                  <td><%= trip.activity.name %></td>
                  <td><%= link_to "View", trip_path(trip) %></td>
                  <td><p class="muted">Delete</p></td>
                  <td>
                    <% if trip.plan.nil? %>
                      &nbsp;
                    <% else %>
                      <%= link_to plan_path(trip.plan) do %><span class="glyphicon glyphicon-ok"><% end %></span>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </table>
        <% else %>
          <% if @trips.empty? %>
            <%= @group.name %> has no trips planned, but you can see <%= link_to "past trips", group_path( id: @group.id, :type => "past" ) %>
          <% else %>
            <h3>Upcoming Trips</h3>
            (or view <%= link_to "past trips", group_path( id: @group.id, :type => "past" ) %>)
            <table class="table table-striped table-hover">
              <thead>
                <tr>
                  <td><b>Trip Date</b></td>
                  <td><b>Trip Location</b></td>
                  <td><b>Trip Activity</b></td>
                  <td><b></b></td>
                  <td><b></b></td>
                  <td><b>Plan?</b></td>
                  <td><b></b></td>
                </tr>
              </thead>  
              <% @trips.each do |trip| %>
                <tr>
                  <td><%= trip.date.strftime("%b %d, %Y") %></td>
                  <td><%= trip.location.name %></td>
                  <td><%= trip.activity.name %></td>
                  <td><%= link_to "View", trip_path(trip) %></td>
                  <td><%= link_to "Edit", edit_trip_path(trip) %></td>
                  <td><%= link_to 'delete', url_for(action: :destroy, id: trip.id),method: :delete, data: {confirm: "Are you sure?"} %></td>
                  <td>
                    <% if trip.plan.nil? %>
                      &nbsp;
                    <% else %>
                      <%= link_to plan_path(trip.plan) do %><span class="glyphicon glyphicon-ok"><% end %></span>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </table>
          <% end %>
        <% end %>
      <% end %>
  </div>