config/routes.rb
Cabra::Application.routes.draw do
  devise_for :users

  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout
  end

  resources :groups
  resources :leaders
  resources :leadernotes
  resources :locations
  resources :trips
  resources :activities
  resources :users
  resources :reports
  resources :plans do
    member do
      post 'add_trips'
      patch 'confirm_plan'
    end
  end

  root to: "trips#index"

end

app/models/plan.rb
class Plan < ActiveRecord::Base
  belongs_to :group
  belongs_to :leader

  has_many :trips

  before_create :create_unique_id

  validates :unique_identifier, uniqueness: true

  validates_presence_of :group, :leader

  def confirmed?
    self.confirmation?
  end

  def full_name
    first_name + " " + last_name
  end

  def to_param
    unique_identifier
  end

  def create_unique_id
    begin
      self.unique_identifier = SecureRandom.urlsafe_base64(6).downcase
    end while self.class.exists?(:unique_identifier => unique_identifier)
  end

end

app/models/plans.rb
class Plans < ActiveRecord::Base
  belongs_to :group
  
  has_many :trips
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :confirm_plan]
  # load_and_authorize_resource

  layout :public_layout

  def index
    @plans = Plan.all.order('created_at DESC')
  end
  def new
    @plan = Plan.new
  end
  def create
    @plan = Plan.new(plan_params)
    if @plan.save
      if @plan.trips.empty?
        @possible = @plan.group.trips.adding_trips
        render "add_trips"
      else
        redirect_to plans_path, notice: "Plan successfully created"
      end
    else
      render "new"
    end
  end
  def show
    @plan = Plan.find_by_unique_identifier(params[:id])
    @trips = @plan.trips.order('date ASC')
  end
  def edit
    @plan = Plan.find_by_unique_identifier(params[:id])
    @group = @plan.group
    @possible = @plan.group.trips.adding_trips
    render "add_trips"
  end
  def update
    @plan = Plan.find_by_unique_identifier(params[:id])
    if @plan.update_attributes(plan_params)
      redirect_to plans_path, notice: "Plan successfully updated!"
    else
      render "edit"
    end
  end
  def add_trips
    @plan = Plan.find_by_unique_identifier(params[:id])
    if params[:trips]
      @trips = Trip.find(params[:trips])
      @trips.each do |trip|
        trip.update_attributes(plan_id: @plan.id)
      end
      redirect_to plan_path(@plan), notice: "Trips added to #{@plan.leader.full_name} plan for #{@plan.group.name} (Plan id: #{@plan.unique_identifier})"
    else
      redirect_to plans_path, notice: "No trips added to #{@plan.leader.full_name} plan for #{@plan.group.name} (Plan id: #{@plan.unique_identifier})"
    end
  end
  def confirm_plan
    @plan = Plan.find_by_unique_identifier(params[:id])
    @plan.update_attributes(plan_params)
    @plan.confirmation = Time.now
    if @plan.save
      redirect_to plan_path(@plan), notice: "Your trips have been confirmed! We will be in touch as your trips get closer!"
    else
      redirect_to plan_path(@plan), notice: "This plan has already been confirmed, your trips are confirmed."
    end
  end
  def destroy
    @plan = Plan.find_by_unique_identifier(params[:id])
    @plan.destroy
    redirect_to plans_path, notice: "Plan destroyed"
  end

    private

    def plan_params
      params.require(:plan).permit(:unique_identifier, :group_id,
                                  :leader_id, :plan_sent)
    end

    def public_layout
      if user_signed_in?
        "application"
      else
        "public"
      end
    end
end

app/views/plans/_form.html.erb
<%= simple_form_for(@plan) do |f| %>
  <% if @plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% @plan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :group_id, collection: Group.all.order('name ASC'), label_method: :name %>

  <%= f.input :leader_id, collection: Leader.all.order('first_name ASC'), label_method: :full_name %>

  <%= f.submit class: "btn" %>

<% end %>

app/views/plans/_list.html.erb
<% if user_signed_in? %>
  <div class="row">
    <div class="alert alert-danger"><b>You can delete this plan, but it cannot be undone <%= link_to 'click here to delete current plan', @plan, method: :delete, data: { confirm: 'Are you sure you want to delete this plan? This cannot be undone' } %></b></div>
    <div class="alert alert-warning"><%= link_to "Add a trip to this plan", edit_plan_path(@plan) %></div>
  </div>
<% end %>

<div class="row">
<div class="col-md-8">

  <center><h3>Trip Plan for <b><%= @plan.leader.full_name %> (<%= @plan.group.name %>)</b></h3></center>

  <p>We're excited about your upcoming GOAT trips! Each of your upcoming trips should be listed below with the details you need for each. If you have any questions or corrections, feel free to contact our program staff. This link will be available through all of your trips whenever you need to reference it.</p></div>

<div class="col-md-4">
 <!-- <img src="http://goattrips.org/images/GOAT-Primary.jpg" width="200" /> -->
  <div class="well">
    <center>
      <h4><a href="http://goattrips.org/pdfs/GOAT-Release.pdf">Download our waiver</a>&nbsp;&nbsp;<span class="glyphicon glyphicon-edit" aria-hidden="true"></span></h4>
    </center>
    <p>Each participant on a GOAT trip will need to have a signed waiver before the start of the first trip. A signed waiver will cover all of our activities for one year.</p>
  </div>
</div>
</div>

<br /><br />

<% @trips.each_with_index do |trip, index| %>
<h3>Trip #<%= index + 1 %>: <%= trip.activity.name %> on <%= trip.date.strftime("%B %d, %Y") %> <% if user_signed_in? %> (<%= link_to "Edit", edit_trip_path(trip) %>) <% end %></h3>
<div class="row well">
  <div class="col-md-6">
    <div class="row">
      <div class="col-md-6"> <!-- nested in above md-6 -->
        <% if trip.pickup == false %>
          <p>Meet GOAT at <%= trip.location.name %></p>
        <% else %>
          <p class="muted">GOAT will pickup at <%= trip.group.name %>:</p>
        <% end %>
        <h3><%= string_to_time(trip.pickup_time) %></h3>
          <h4></h4>
        <br /><br />
        <% if trip.pickup == false %>
          <p>Departure</p>
        <% else %>
          <p>Return to <%= trip.group.name %> at:</p>
        <% end %>
        <h3><%= string_to_time(trip.dropoff_time) %></h3>
        <hr />
      </div>
      <div class="col-md-6"> <!-- nested in above md-6 -->
        <p>Scheduled number of participants</p>
        <h3><%= trip.scheduled_participants %></h3>

        <br /><br />
        <p>Trip Location</p>
        <h4><%= trip.location.name %></h4>
        <h4><%= trip.location.street %></h4>
        <h4><%= trip.location.city %>, <%= trip.location.state %> <%= trip.location.zip %></h4>
      </div>
    </div>

    <br /><br />
    <p>
      <% if trip.lunch? %>
        -GOAT will be providing lunch for this trip
      <% else %>
        -GOAT will <b>not</b> be providing lunch for this trip
      <% end %>
    </p>
    <p>-Need to know what to bring on a <%= trip.activity.name %> trip? <a href="<%= trip.activity.whattobring %>">here's a list</a></p>

  </div>

  <div class="col-md-6">
    <h4>Directions: <%= link_to trip.full_address, "http://maps.google.com/?q=#{trip.full_address}" %></h4>
    <%= image_tag trip.google_static_image %>
  </div>

</div>
<div class="alert alert-warning" role="alert">In the case of inclement weather, we will plan on climbing at GOAT's indoor climbing facility at 61 Byrdland Dr in Greenville, SC 29607</div>

<br />
<hr />
<br />

<% end %>

app/views/plans/add_trips.html.erb
<h3>Add trips to plan for <%= @plan.group.name %></h3>

<% if @possible.blank? %>

  <h3>There are no upcoming trips scheduled for <%= @plan.group.name %>. Please <%= link_to "create a new trip", trips_path %> to add to this plan.</h3>

<% else %>

  <%= form_tag(add_trips_plan_path(@plan)) do %>
    <% @possible.each do |trip| %>
        <div class="input-group">
          <%= check_box_tag 'trips[]', trip.id %>
          <%= label_tag("#{trip.activity.name} on #{trip.date.strftime("%b %d, %Y")}") %>
        </div>
    <% end %>

    <%= submit_tag("Submit") %>
  <% end %>

<% end %>

app/views/plans/index.html.erb
<%= link_to "Create New Trip Plan", new_plan_path %>&nbsp;<span class="glyphicon glyphicon-new-window"></span>

<h3>Current Trip Plans</h3>

<% if @plans.empty? %>

  <h1>You have no plans yet</h1>

  <h3><%= link_to "Create a new trip plan", new_plan_path %></h3>

<% else %>

  <table class="table table-striped table-hover">
      <thead>
        <tr>
          <td><b>Created</b></td>
          <td><b>Group</b></td>
          <td><b>Leader</b></td>
          <td><b>Edit</b></td>
          <td><b>Link</b></td>
          <td><b>Confirmed?</b></td>
        </tr>
      </thead>

      <% @plans.each do |plan| %>
      <tr>
        <td><%= plan.created_at.strftime("%b/%y") %></td>
        <td><%= plan.group.name %></td>
        <td><%= plan.leader.full_name %></td>
        <td><%= link_to "Edit", edit_plan_path(plan) %></td>
        <td><%= link_to plan_path(plan), plan_path(plan) %></td>
        <td>
          <% if plan.confirmed? %>
            <span class="glyphicon glyphicon-ok"></span>
          <% end %>
        </td>
        <td><%= link_to 'Delete', plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>

  </table>

<% end %>

app/views/plans/new.html.erb
<h3>New Trip Plan</h3>

<%= render 'form' %>

app/views/plans/show.html.erb
<% if user_signed_in? %>
  <% if @plan.confirmed? == false %>
    <center><h1>This plan has not been confirmed</h1></center>
    <br />
  <% end %>
    <div class="row">
      <div class="alert alert-danger"><b>You can delete this plan, but it cannot be undone <%= link_to 'click here to delete current plan', @plan, method: :delete, data: { confirm: 'Are you sure you want to delete this plan? This cannot be undone' } %></b></div>
      <div class="alert alert-warning"><%= link_to "Add a trip to this plan", edit_plan_path(@plan) %></div>
    </div>
<% else %>
  <% if @plan.confirmed? == false %>
    <%= simple_form_for @plan, url: confirm_plan_plan_path do |f| %>
      <%= f.error_notification %>

      <div class="row alert-danger">
        <div class="col-md-4 col-md-offset-4">
        <br />
        Your trips have not yet been confirmed. Please review your proposed trips below and then enter your email to confirm.
        Until your trips have been confirmed, they may be available to other groups.
        Your trips will not be saved for your group until you have confirmed. All confirmed trips will be subject to cancellation policies.
        <br /><br />
        <%= f.input :confirmation_email %>

        <%= f.button :submit, 'Confirm Trips' %>
        <br /><br />
      </div>
    </div>
      <% end %>
  <% end %>
<% end %>
<br /><br />

<div class="row">
<div class="col-md-8">

  <center><h3>Trip Plan for <b><%= @plan.leader.full_name %> (<%= @plan.group.name %>)</b></h3></center>

  <p>We're excited about your upcoming GOAT trips! Each of your upcoming trips should be listed below with the details you need for each. If you have any questions or corrections, feel free to contact our program staff. This link will be available through all of your trips whenever you need to reference it.</p></div>

<div class="col-md-4">
 <!-- <img src="http://goattrips.org/images/GOAT-Primary.jpg" width="200" /> -->
  <div class="well">
    <center>
      <h4><a href="http://goattrips.org/pdfs/GOAT-Release.pdf">Download our waiver</a>&nbsp;&nbsp;<span class="glyphicon glyphicon-edit" aria-hidden="true"></span></h4>
    </center>
    <p>Each participant on a GOAT trip will need to have a signed waiver before the start of the first trip. A signed waiver will cover all of our activities for one year.</p>
  </div>
</div>
</div>

<br /><br />

<% @trips.each_with_index do |trip, index| %>
<h3>Trip #<%= index + 1 %>: <%= trip.activity.name %> on <%= trip.date.strftime("%B %d, %Y") %> <% if user_signed_in? %> (<%= link_to "Edit", edit_trip_path(trip) %>) <% end %></h3>
<div class="row well">
  <div class="col-md-6">
    <div class="row">
      <div class="col-md-6"> <!-- nested in above md-6 -->
        <% if trip.pickup == false %>
          <p>Meet GOAT at <%= trip.location.name %></p>
        <% else %>
          <p class="muted">GOAT will pickup at <%= trip.group.name %>:</p>
        <% end %>
        <h3><%= string_to_time(trip.pickup_time) %></h3>
          <h4></h4>
        <br /><br />
        <% if trip.pickup == false %>
          <p>Departure</p>
        <% else %>
          <p>Return to <%= trip.group.name %> at:</p>
        <% end %>
        <h3><%= string_to_time(trip.dropoff_time) %></h3>
        <hr />
      </div>
      <div class="col-md-6"> <!-- nested in above md-6 -->
        <p>Scheduled number of participants</p>
        <h3><%= trip.scheduled_participants %></h3>

        <br /><br />
        <p>Trip Location</p>
        <h4><%= trip.location.name %></h4>
        <h4><%= trip.location.street %></h4>
        <h4><%= trip.location.city %>, <%= trip.location.state %> <%= trip.location.zip %></h4>
      </div>
    </div>

    <br /><br />
    <p>
      <% if trip.lunch? %>
        -GOAT will be providing lunch for this trip
      <% else %>
        -GOAT will <b>not</b> be providing lunch for this trip
      <% end %>
    </p>
    <p>-Need to know what to bring on a <%= trip.activity.name %> trip? <a href="<%= trip.activity.whattobring %>">here's a list</a></p>

  </div>

  <div class="col-md-6">
    <h4>Directions: <%= link_to trip.full_address, "http://maps.google.com/?q=#{trip.full_address}" %></h4>
    <%= image_tag trip.google_static_image %>
  </div>

</div>
<div class="alert alert-warning" role="alert">In the case of inclement weather, we will make alternate plans the day of the scheduled trip</div>

<br />
<hr />
<br />

<% end %>