config/routes.rb
Cabra::Application.routes.draw do
  devise_for :users

  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout
  end

  resources :groups
  resources :leaders
  resources :leadernotes
  resources :locations
  resources :trips
  resources :activities
  resources :users
  resources :reports
  resources :plans do
    member do
      post 'add_trips'
      patch 'confirm_plan'
    end
  end

  root to: "trips#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.has_role?(:admin)
      can :manage, :all
    elsif user.has_role?(:reporter)
      cannot :create, Trip
      can :read, Trip
      can :create, Report
    else
      can :read, Trip
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  has_many :trips

end

app/models/area.rb
class Area < ActiveRecord::Base
  belongs_to :trip
  belongs_to :location
end

app/models/confirmation.rb
class Confirmation < ActiveRecord::Base
  belongs_to :plan

  validates_presence_of :plan_id
  validates_presence_of :email

  validates :plan_id, uniqueness: true

  # before_save :ensure_not_confirmed

  # def ensure_not_confirmed
  #   return if self.plan.confirmed?
  # end
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :plans
  has_many :trips
  has_many :leaders
  has_many :students

  validates :name, uniqueness: true

end

app/models/groups.rb
class Groups < ActiveRecord::Base
  has_many :plans
  has_many :trips
  has_many :leaders
  has_many :students
end

app/models/leader.rb
class Leader < ActiveRecord::Base
  belongs_to :group
  has_many :plans
  has_many :leadernotes

  validates_presence_of :first_name, :last_name, :group_id

  def full_name
    first_name + " " + last_name
  end

end

app/models/leadernote.rb
class Leadernote < ActiveRecord::Base
  belongs_to :leader
  belongs_to :user



end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :trips

  def full_address
    street + " " + city + " " + state + " " + zip
  end

end

app/models/locations.rb
class Locations < ActiveRecord::Base
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  belongs_to :group
  belongs_to :leader

  has_many :trips

  before_create :create_unique_id

  validates :unique_identifier, uniqueness: true

  validates_presence_of :group, :leader

  def confirmed?
    self.confirmation?
  end

  def full_name
    first_name + " " + last_name
  end

  def to_param
    unique_identifier
  end

  def create_unique_id
    begin
      self.unique_identifier = SecureRandom.urlsafe_base64(6).downcase
    end while self.class.exists?(:unique_identifier => unique_identifier)
  end

end

app/models/plans.rb
class Plans < ActiveRecord::Base
  belongs_to :group
  
  has_many :trips
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :trip
  belongs_to :user

  scope :current_year, -> { where('extract(year from created_at) = ?', Time.zone.now.year) }
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :group
end

app/models/students.rb
class Students < ActiveRecord::Base
  belongs_to :group
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to :group
  belongs_to :plan
  belongs_to :location
  belongs_to :activity

  has_one :report

  delegate :confirmed?, to: :plan
  delegate :full_address, to: :location

  scope :future, -> { where("date > ?", Date.today) }
  scope :past, -> { where("date <= ?", Date.today) }
  scope :year, -> { where("extract(year from date) = ?", Date.today.year) }
  scope :need_report, -> { select { |trip| trip.report.blank? } }
  scope :adding_trips, -> { where("plan_id IS ?", nil) }

  validates_presence_of :date, :group_id, :location_id, :activity_id, :pickup_time, :dropoff_time


  def google_static_image
    "http://maps.googleapis.com/maps/api/staticmap?maptype=roadmap&sensor=false \
    &center=Greenville%20SC&size=500x300 \
    &markers=color:green%7CGreenville%20SC \
    &markers=color:red%7Clabel:G%7C#{self.full_address} \
    &key=#{ENV['GOOGLE_MAPS_API_KEY']}"
  end
end

app/models/trip_types.rb
class TripTypes < ActiveRecord::Base
  
end

app/models/trips.rb
class Trips < ActiveRecord::Base
  belongs_to :group
  belongs_to :plan

  has_one :trip_type
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :leadernotes
  has_many :reports

  # Roles defined for cancancan (instead of adding roles model)
  ROLES = %i[admin regular reporter].freeze

  # Roles logic to covert string above to/from integers
  def roles=(roles)
    roles = [*roles].map { |r| r.to_sym }
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.inject(0, :+)
  end

  def roles
    ROLES.reject do |r|
      ((roles_mask.to_i || 0) & 2**ROLES.index(r)).zero?
    end
  end

  def has_role?(role)
    roles.include?(role)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GOAT - Alpha</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar-wrapper">
      <div class="container">

        <div class="navbar navbar-inverse navbar-static-top" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <%= link_to "Alpha", trips_path, class: "navbar-brand" %>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <% if current_user && current_user.has_role?(:admin) %>
                  <li class="<%= is_active?(leaders_path) %>"><%= link_to "Leaders", leaders_path %></li>
                  <li class="<%= is_active?(groups_path) %>"><%= link_to "Groups", groups_path %></li>
                  <li class="<%= is_active?(trips_path) %>"><%= link_to "Trips", trips_path %></li>
                  <li class="<%= is_active?(plans_path) %>"><%= link_to "Plans", plans_path %></li>
                <% end %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">User</a></li>
                    <% if current_user && current_user.has_role?(:admin) %>
                      <li><%= link_to "Manage Users", users_path %></li>
                      <li><%= link_to "Manage Locations", locations_path %></li>
                      <li><%= link_to "Add activity", activities_path %></li>
                    <% end %>
                    <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
        </div>

      </div>
    </div>


<div class="container">

  <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert alert-warning" %>
  <% end %>

  <%= yield %>
</div>

</body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cabra</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <style type="text/css">
    body { padding-top: 70px; }
  </style>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">
        <img src="http://goattrips.org/images/GOAT-Horizontal.jpg" height="25" />
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">

  <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert alert-warning" %>
  <% end %>

  <%= yield %>

</div>
</body>
</html>